services:
  inventory:
    build: ./services/inventory
    ports:
      - 8000:8000
    environment:
      - PORT=8000
  products:
    build: ./services/products
    ports:
      - 8001:8000
    environment:
      - INVENTORY_RPC=inventory
      - PORT=8000
      