openapi: 3.0.0
info:
  title: shop
  version: 0.1.9

servers:
  - url: http://localhost:3000/inventory

paths:
  /:
    get:
      summary: Get inventory
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema: 
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    stock:
                      type: integer 
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema: 
                type: object
                properties:
                  message:
                    type: string
                    example: Internal Server Error